---
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout

      - restore_cache:
          keys:
            - gradle-cache

      - run:
          name: Fetch dependencies
          command: ./gradlew dependencies --refresh-dependencies

      - run:
          name: Run gradle build
          command: ./gradlew clean build --stacktrace

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build and publish Docker image
          command: |
            chmod +x ./scripts/docker-util.sh
            case ${CIRCLE_BRANCH} in
                master)
                    ./scripts/docker-build.sh -b -p
                    ;;
                develop)
                    ./scripts/docker-build.sh -b -p -t beta
                    ;;
                *)
                    ./scripts/docker-build.sh -b -t dev
                    echo "Publish not required for branch: ${CIRCLE_BRANCH}"
                    ;;
            esac